# Generated by Django 4.1.7 on 2023-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200805_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='mode',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank', 'Bank'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Crypto', 'Crypto')], default='Mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasershippingdetail',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Busia', 'Busia'), ('Kakamega', 'Kakamega'), ('Nyeri', 'Nyeri')], default='Nairobi', max_length=255),
        ),
    ]
